### ISSUE TITLE
How to access database

### ISSUE THREAD

**Issue by sanmisasi** [arifbsmrstu/My-Doctor#1]
since it is a firebase database how can I view the database details

**Comment by arifbsmrstu** [comment]
Here i used my personal gmail account for firebase database. You can create your personal database from https://console.firebase.google.com/

**Comment by sanmisasi** [comment]
But how can I able to know the entries.. ie.. tables.. I am cannot register with this app ..How to modify the database to make the appliaction run on my system

**Comment by arifbsmrstu** [comment]
You will get Users table entries from Patient.java class and get Doctors entries from Doctors.java class. In this project i have added doctor profile manually. Other table will generate automatically from the code.

**Comment by sanmisasi** [comment]
Can you give a little more explanation on this.. or a screenshot of the database tables..Since I am new to development.. I could not make it..PLease help me..

**Comment by sanmisasi** [comment]
I am getting authentication failed.. For patient registration what should be the entries in the table

**Comment by arifbsmrstu** [comment]
This is not database problem. You need to enable Email/Password authentication from firebase console. Make sure your app is connected with your own firebase account. Database will create automatically.

**Comment by sanmisasi** [comment]
OK..What about doctor login email and password

**Comment by sanmisasi** [comment]
ok.. what about doctor login

**Comment by arifbsmrstu** [comment]
I have added doctor manually. 
![doc](https://user-images.githubusercontent.com/12998006/37949206-7178b9f4-31b5-11e8-8959-c40bf7c9cf1b.png)
For id you need to create authentication manually also.

**Comment by sanmisasi** [comment]
Thank yoi

**Comment by sanmisasi** [comment]
One more doubt..what about if  the patient(user) sign in with his email id and password

**Comment by sanmisasi** [comment]
Patient side the app is working.. But when I sign in doctor only empty page in Doctor Home page

**Comment by arifbsmrstu** [comment]
If patient sent any message to doctor then the doctor will able to see the message list in his home.

**Comment by sanmisasi** [comment]
we sign in for doctor with already created email and password.. then what about doctors id type name.. once the doctor sign in I have only online status attribute in the table what name id image url attributes

**Comment by sanmisasi** [comment]
Also I have a issue in sending message.. When I click on the message symbol the app stops with "unfortunately the app has stopped"..
