### ISSUE TITLE
I have tried to run your your code, but after many attempts , I found out that R.java class was missing. 

### ISSUE THREAD

**Issue by vastav-adi** [arifbsmrstu/My-Doctor#3]
I have cleaned, rebuilt, restructured the project many times over.
Invalidated and cleared cache,
but the R.java file still remains missing.

**Comment by Ferdib-Al-Islam** [comment]
> 
> 
> I have cleaned, rebuilt, restructured the project many times over.
> Invalidated and cleared cache,
> but the R.java file still remains missing.

[Check this video](https://www.youtube.com/watch?v=ahf6vKQMkwM)
It may help you.

**Comment by ArthurBonsu** [comment]
Okay, what about re-running on a different android studio version, does the
R.java code still act the same way?

**Comment by ArthurBonsu** [comment]
I will check on it soon.

**Comment by arifbsmrstu** [comment]
With various update of android studio, we need to modify it's some configuration. Also this is an old project now, things on android and firebase are changing so fast. You need to find out the current best configuration or using old configuration.

**Comment by arifbsmrstu** [comment]
> I have cleaned, rebuilt, restructured the project many times over.
> Invalidated and cleared cache,
> but the R.java file still remains missing.

Hope you have found your solution, Thanks @Ferdib-Al-Islam

**Comment by ArthurBonsu** [comment]
Okay Ariful, I will do that, been quite busy of late but I will sure do all
the updates

**Comment by arifbsmrstu** [comment]
It's my pleasure that folks are loving my code, but I have changed my track that's why i have failed to maintain my old code. I hope the best for you.

**Comment by ArthurBonsu** [comment]
Thanks a lot

**Comment by Ferdib-Al-Islam** [comment]
My Pleasure, @arifbsmrstu 
Close the issue. :D
